import { Inter } from "next/font/google";

import "../../globals.css";
import { Toaster, toast } from "sonner";
import SidePanel from "@/components/(dashboard)/sidePanel";
const inter = Inter({ subsets: ["latin"] });
const additionalClasses = "text-[#050505]";
0;

const bodyClasses = `${inter.className} ${additionalClasses}`;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={bodyClasses}>
        <Toaster richColors />
        <SidePanel />
        {children}
      </body>
    </html>
  );
}
