import { Inter } from "next/font/google";
import "../../globals.css";
import { Toaster } from "sonner";
import SidePanel from "../../../components/(dashboard)/sidePanel";
import SearchPanel from "../../../components/(dashboard)/searchPanel";
const inter = Inter({ subsets: ["latin"] });
const additionalClasses = "text-[#050505] bg-[#fafafa]";
import styles from "./styles.module.css";

const bodyClasses = `${inter.className} ${additionalClasses} ${styles.dashboard}`;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={bodyClasses}>
        <Toaster richColors />
        <div className="flex flex-row">
          <SidePanel />
          <div className="flex w-full flex-col">
            <div className="mx-auto w-[90%]">
              <SearchPanel />
            </div>

            <div className="w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
