import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });
const additionalClasses = "text-[#050505]";

const bodyClasses = `${montserrat.className} ${additionalClasses}`;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyClasses}>{children}</body>
    </html>
  );
}
