import { Poppins } from "next/font/google";
import { Toaster, toast } from "sonner";
const additionalClasses = "text-[#050505]";
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

const bodyClasses = `${poppins.className} ${additionalClasses}`;
import "../globals.css";
import Navbar from "@/components/navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={bodyClasses}>
      <body>
        <Toaster richColors />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
